'''
Akond Rahman
Mar 25, 2018
Constants needed to detect smells
'''


PP_EXT = '.pp'
CH_EXT = '.rb'
CH_DIR = 'recipes'
TEST_DIR_SPEC = 'spec/'
TEST_DIR_ACCE = 'acceptance/'
DOT = '.'
EXCEPTION = 'EXCEPTION:::'
BASH_CMD  = 'bash'
BASH_FLAG = '-c'
### PUPPET LINT AND ITS RULES
PP_LINT_TOOL = 'puppet-lint'

### OUTPUT TMP LOG
REDIRECT_NEW = '>'
REDIRECT_APP = '>>'
OUTPUT_TMP_LOG = 'CODE.SMELL.TEMP.LOG'
FILE_OPEN_MODE = 'rU'
TMP_DES_TXT = 'tmp.txt'
### month constants
INV_MON_CON = '0000-00'
###OUTPUT HEADERS
SMELL_HEADER1 = "MISS_DFLT,INCO_NAME,CPLX_EXPR,DUPL_ENTI,MSPL_ATTR,IMPR_ALIG,"
SMELL_HEADER2 = "INVA_PROP,INCO_TASK,DEPE_STMT,IMPR_QUOT,LONG_STMT,INCO_COND,UNGU_VARI,"
SMELL_HEADER3 = "MULT_ABST,UNNE_ABST,MISS_ABST,IMPE_ABST,INSU_MODU,DEFI_ENCA,TOTA,"
SMELL_HEADER  = "MONTH,FULL_PATH,MONT_PATH," + SMELL_HEADER1 + SMELL_HEADER2 + SMELL_HEADER3 + "DEFECT"
